# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3496f5da22ecb646a15b8215c2184d40d0b0229ef599d31e16d54fae525fd7741beeb15efe6846d08e9c7862671c6f85a6a9001f4a81c76be283982d9dcdc5d3

test:
  secret_key_base: 62ed3148dd59e5517304f0f87b0506bf8d8b088e25a9fc7f8d13f84565f23ea21b585e129d4b5901c59a004303366b1b6980ede04d1eee267e73f8f23a49a98b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
